kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: secops
rules:
- apiGroups: [""] # “” indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
