apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secops
  namespace: default
subjects:
- kind: User
  name: user2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secops
  apiGroup: rbac.authorization.k8s.io
